### ISSUE TITLE
UI animations

### ISSUE THREAD

**Issue by Lemmmy** [ouzo-team/ouzo-game#23]
UI controls can stack animations which have a duration, easing function, value to modify, from, to

something like
this->AnimateFloat(650, &this->x, 0, 60, EasingFunctions::EASE_IN_OUT_CUBIC);

where time is specified in ms and the value to modify is a pointer

**Comment by Lemmmy** [comment]
Perhaps make the following method signatures:

`AnimateFloat(long start, long finish, float *val, float from, float to, EasingFunctions easing)`
`AnimateFloat(long duration, float *val, float from, float to, EasingFunctions easing)`

where the second one uses the current time in ms as the start point

**Comment by Lemmmy** [comment]
See Trello for to-do list.

**Comment by GeorgeMcKinlay** [comment]
Why double pointer?

**Comment by Lemmmy** [comment]
sorrie fixed

**Comment by GeorgeMcKinlay** [comment]
It'd probably be wise to use a flag parameter for the easing:
```
this->AnimateFloat(650, &this->, 0, 60, Easing::EASE_IN | Easing::EASE_OUT | Easing::EASE_CUBIC);
```

Also, use templates to have it figure out the type on its own instead of making a trillion overloads.
